remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
title: [TFG(Re)Search]
description: [Página del proyecto de innovación docente para Trabajos de Fin de Grado en Matemáticas de la Universidad de Granada]
include:
  - README.md
  - Programa_Sesion_1.md
