theme: jekyll-theme-cayman
defaultLang: es
relative_links:
  enabled: true
  collections: true
title: [TFG(Re)Search]
description: [Página del proyecto de innovación docente para Trabajos de Fin de Grado en Matemáticas de la Universidad de Granada]
logo: /assets/img/logo-tri.png
include:
  - README.md
  - Programa_Sesion_1.md
  - Participantes.md
