remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: [TFG(Re)Search]
description: [Página del proyecto de innovación docente para Trabajos de Fin de Grado en Matemáticas de la Universidad de Granada]
